# Generated by Django 4.2 on 2023-04-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='grade',
            field=models.CharField(blank=True, choices=[('A+', '100'), ('B+', '85')], max_length=2, null=True),
        ),
    ]
