# Generated by Django 4.2 on 2023-04-08 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_todo_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitems',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='todoitems',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todoitems',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoitems',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='todoitems',
            name='todo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.todo'),
        ),
    ]
